version: '3.7'

services:
  web:
    build: .
    command: uvicorn crypto_scan.__main__:app --reload --host 0.0.0.0 --port 8000 
    container_name: cryptoscan_api
    volumes:
      - .:/application
    dns:
      - 8.8.8.8
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on: 
      - db
  db:
    image: postgres:12.1-alpine
    container_name: cryptoscan_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  postgres_data:
